name: CI

on:
  push:
    branches:
      - master
      - next
      - beta
      - alpha
    tags-ignore:
      - '**'
  pull_request:
    branches:
      - '*'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7.32.1
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'
      - name: 安装依赖
        run: pnpm install --frozen-lockfile
      - name: 执行 Lint
        run: pnpm run lint
  release:
    name: Release
    runs-on: ubuntu-latest
    needs:
      - lint
    # Trigger release for only pushes to branches defined above
    if: ${{github.event_name == 'push'&& (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/next' || github.ref == 'refs/heads/beta' ) }}
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7.32.1
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'
      - name: 安装依赖
        run: pnpm install --frozen-lockfile
      - name: 构建
        run: pnpm run build
      # Release using semantic-release.
      # While this runs on all branches, it will only release latest from master
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
