name: CI

on:
  push:
    branches:
      - master
      - next
      - beta
      - alpha
    tags-ignore:
      - '**'
  pull_request:
    branches:
      - '*'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 6.32.9
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'pnpm'
      - name: 安装依赖
        run: pnpm install --frozen-lockfile
      - name: 执行 Lint
        run: pnpm run lint
  release:
    name: Release
    runs-on: ubuntu-latest
    needs:
      - lint
    # Trigger release for only pushes to branches defined above
    if: ${{github.event_name == 'push'&& (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/next' || github.ref == 'refs/heads/beta' ) }}
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 6.32.9
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'pnpm'
      # Release using semantic-release.
      # While this runs on all branches, it will only release latest from master
      - uses: docker://ghcr.io/virgoone/semantic-release-action:latest
        with:
          branches: |
            [
              'master',
              'next',
              {
                name: 'beta',
                prerelease: true
              },
              {
                name: 'alpha',
                prerelease: true
              }
            ]
          tag_format: 'v${version}'
          extends: '@semantic-release/apm-config'
          plugins: |
            ['@semantic-release/commit-analyzer', '@semantic-release/release-notes-generator', '@semantic-release/changelog', '@semantic-release/npm', '@semantic-release/github', '@semantic-release/git']
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
